version: "3"
services:
  server:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      NODE_ENV: production
    image: correction-bot:v1.0.0
    container_name: correction-bot
    volumes:
      - ../config:/app/config
